app/assets/stylesheets/_footer.scss, app/views/layouts/_footer.html.haml
=> SetFooter_01

Capfile, config/deploy.rb, config/deploy/production.rb, config/deploy/staging.rb, config/unicorn.rb
#what
Capistranoの導入の実装。
#why
自動でデプロイできるようにするため。
修正ファイルが多そうだったので、ブランチ作りました。
=> Deploy capistrano introduction

app/assets/stylesheets/_footer.scss, app/views/layouts/_footer.html.haml
footer.html.haml 及び footer.scssのクラス名表記の変更
チーム内でのBEMルールに則るため。
=> Footerクラス名変更

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_header-image.scss, app/assets/stylesheets/modules/_navigation.scss, app/assets/stylesheets/modules/_user-show.scss, app/controllers/users_controller.rb, app/views/users/show.html.haml
What
ユーザマイページのhaml と scss のクラス名を
freemarket_sample_63aのBEMルールに従って変更しましたので、
確認をお願いします。
BEMについてのルール（63期aチーム）
ブロックについて
①Rails routesで確認してそのviewに向かう
contro#actionを必ずブロックの接頭辞にする。
＃(シャープ)は-(ハイフン)で置き換える
例）tops#index　→　tops-index　
②接頭辞に-（ハイフン）で単語を繋げてブロックとすることは可とする。
例）tops-index-header
tops-index-contents
tops-index-content など
③該当のviewのブロックについては全て上記接頭辞を付帯する。
④BEMはそれぞれ1つまでとする。
例）.tops-index-header__inner—btn
　　.tops-index →B
　　.header　　→E
　　.innner--btn →M
.scssについて
①名前は「接頭辞.scss」とし、同じ接頭辞を含むブロックについては
全て同ファイルに記載することとする。
②ファイル内ではブロック単位で分割して記載する。
.tops-index{
}
.tops-index-header{
　&__inner{
　　&—btn{
　　}
　}
}
Why
今後のアプリケーション開発にて、BEMルールの統一化が重要なため
=> Refactoring user page(チームのBEMルールに従ってクラス名を変更)

app/views/layouts/_purchase-btn.html.haml
出品画面へ遷移できる様にパスを指定して現在ログインしているユーザーのidがパスに入るようにしました。
出品画面への流れを作るため。
=> Trade page new

app/views/layouts/_purchase-btn.html.haml
ログイン状態とログインしていない状態で出品アイコンを押した際の遷移先を条件分岐しました。
条件分岐しないとエラーが起きる。
=> If user login

README.md, app/models/item.rb, app/models/shipping.rb, app/models/trade.rb, app/models/user.rb, db/migrate/20200224034629_add_buyerid_to_items.rb, db/migrate/20200224082648_drop_trade_table.rb, db/migrate/20200224094746_add_buyerid_to_items.rb, db/schema.rb, test/models/trade_test.rb
tradesテーブルの内容をitemsテーブルに統合しました。
コードレビューをお願いします。
プルリクをmerge後、developmentブランチからpullしてからは、
下記の操作を実行してください
1. merge後のdevelopmentブランチをpullする
1. rails db:migrateを実行する。
1. tradeモデルとテストコードを手作業で削除する。
- app/models/trade.rb
- spec/models/trade_spec.rb
- spec/factories/trades.rb
管理するテーブルを削減することで、アプリケーション開発の工数を削減できるため。
=> Merge trade table into item table

app/assets/stylesheets/_header.scss, app/views/layouts/_header.html.haml
トップページヘッダーのリファクタリング
BEMを統一することで、見やすいコードとなる。
=> リファクタリング(トップページヘッダー)

app/assets/stylesheets/modules/_registrations_new.scss, app/views/devise/registrations/new.html.haml
#why
aタグが全域に影響していたため、影響範囲を限定する必要があった。
＃what
他ページに影響がないか。
=> refactoring

app/assets/javascripts/creditcards.coffee, app/assets/javascripts/items.coffee, app/assets/javascripts/payjp.js, app/assets/stylesheets/creditcards.scss, app/controllers/creditcards_controller.rb, app/helpers/creditcards_helper.rb, app/views/creditcards/new.html.haml, app/views/creditcards/show.html.haml, app/views/items/new.html.haml, app/views/layouts/application.html.haml, app/views/users/show.html.haml, config/routes.rb, spec/controllers/creditcards_controller_spec.rb, spec/helpers/creditcards_helper_spec.rb, spec/views/creditcard/new.html.haml_spec.rb
クレジットカード機能を追加しました。
クレジットカードモデルをユーザーモデルにネストさせてあります。
users#showページの支払い方法の所に遷移先のリンクを貼りました。
マークアップはまだです。
ユーザーが売買をする際にクレジットカードの情報が必須である為。
=> Pay jp page

Gemfile.lock, app/models/item.rb, db/seeds.rb, db/seeds/address.rb, db/seeds/category.rb, db/seeds/category_size.rb, db/seeds/item.rb, db/seeds/product_size.rb
出品機能と購入機能を実装するために
テストデータの作成が必要なため。
前回のデータベース修正に伴い、
各マスタ、ユーザー、itemのシードデータ作成処理(seeds.rb)を再構築しました。
product_sizeのシードデータの作成。
category_sizeのシードデータの作成。
addressのシードデータの作成。
itemテーブルのシードデータの対応。
=> itemテーブルのSEEDデータ作成のための修正。

Gemfile.lock, app/assets/stylesheets/modules/_creditcards-show.scss, app/views/creditcards/show.html.haml
#why
クレジットカードの登録後、登録したカードのインターフェイスが必要なため。
＃what
必要な情報が表示できているか。
・カードナンバー末尾４桁
・有効期限
不必要な情報が表示されていないか。
・カードナンバー全部
・CVC
[![Screenshot from Gyazo](https://gyazo.com/82a412d338bb92f824d234a2aed518a4/raw)](https://gyazo.com/82a412d338bb92f824d234a2aed518a4)
=> Creating a credit card confirmation page

app/controllers/items_controller.rb, app/models/address.rb, app/models/item.rb, app/models/trade.rb, app/models/user.rb, app/views/items/new.html.haml, app/views/layouts/_purchase-btn.html.haml, config/locales/en.yml, config/routes.rb, db/migrate/20200303101022_create_trades.rb, db/migrate/20200303102404_remove_columns_from_items.rb, db/schema.rb, db/seeds/item.rb, spec/factories/trades.rb, spec/models/trade_spec.rb
＃why
開発を進めていくにあたって購入履歴を記録するテーブルが個別に必要と感じたため。
＃what
テーブルを作成後の動作に問題ないかどうか。
[![Screenshot from Gyazo](https://gyazo.com/ef357a8d12b00fd3af9f62cfc3c4c2dd/raw)](https://gyazo.com/ef357a8d12b00fd3af9f62cfc3c4c2dd)
[![Screenshot from Gyazo](https://gyazo.com/60bea58bb86253c5986506e1ce910b18/raw)](https://gyazo.com/60bea58bb86253c5986506e1ce910b18)
=> トレードテーブルの追加、及び関連するroute,controller,viewの修正

app/controllers/items_controller.rb, app/models/item.rb, app/models/item_image.rb, app/views/items/new.html.haml
画像投稿可能になりました。
ですが、まだプレビュー表示は不可です。
Itemテーブルに紐づいたimageを登録したい為。
[![Image from Gyazo](https://i.gyazo.com/794258a2272313ba6872fafb9f7dad77.gif)](https://gyazo.com/794258a2272313ba6872fafb9f7dad77)
=> Item image upload

app/controllers/items_controller.rb, app/controllers/tops_controller.rb, app/views/items/show.html.haml, app/views/tops/index.html.haml, config/initializers/carrierwave.rb
#why
登録した商品の詳細情報を表示させる機能が必要なため。
#what
登録された商品から必要な情報が取得でき、適切に表示されているか。
※商品購入ボタン、商品編集ボタンは別途、実装します。
[![Screenshot from Gyazo](https://gyazo.com/56a5f33806bc8ec801a78b993a9fb5b4/raw)](https://gyazo.com/56a5f33806bc8ec801a78b993a9fb5b4)
[![Screenshot from Gyazo](https://gyazo.com/b96a25c742e031e8763a1bc7307b5771/raw)](https://gyazo.com/b96a25c742e031e8763a1bc7307b5771)
[![Screenshot from Gyazo](https://gyazo.com/17183ffd0155c09eb64fcc64be9bd63f/raw)](https://gyazo.com/17183ffd0155c09eb64fcc64be9bd63f)
=> 商品詳細表示機能の実装

app/assets/javascripts/address.coffee, app/assets/stylesheets/address.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_address-edit.scss, app/views/address/edit.html.haml
住所編集画面のscssを整理
住所変更昨日はフリマアプリにおいて必須項目であるため。
=> 住所編集画面フロント実装

app/assets/stylesheets/modules/_address-new.scss, app/controllers/addresses_controller.rb, app/controllers/tops_controller.rb, app/models/address.rb, app/views/addresses/index.html.haml
住所登録/編集/削除時のフラッシュメッセージ実装
https://gyazo.com/70ed674cc8eacddb31025b1b9930ba47
フラッシュメッセージすることで、ユーザーに登録ができたかどうかを分かりやすくするため。
=> 住所登録/編集/削除時のフラッシュメッセージ実装

app/assets/stylesheets/modules/_addresses-index.scss, app/models/address.rb, app/views/addresses/index.html.haml
住所一覧画面のViewを整理
https://gyazo.com/601c9e26b9f79c93c70b4f0a928461b8
これまでの状態だと、住所一覧が横並びになってしまい見辛く、修正が必要であったから。
=> 住所一覧画面のviewを整理

app/controllers/items_controller.rb, app/models/item.rb, app/models/item_image.rb, app/views/items/edit.html.haml, app/views/items/new.html.haml, app/views/items/show.html.haml, config/locales/ja.yml, spec/factories/addresses.rb, spec/factories/brand.rb, spec/factories/categories.rb, spec/factories/item_images.rb, spec/factories/items.rb, spec/factories/product_sizes.rb, spec/factories/shippingway.rb, spec/factories/trades.rb, spec/models/address_spec.rb, spec/models/item_spec.rb, spec/models/trade_spec.rb
#why
・モデルが正常に動作するかの各員要件としてテストが必要であるため。
・いくつか不具合が発生していたため、修正対応を実施。
#what
・バリデーションに対応したテストができているか
・商品がファイルなしで投稿された際に画像を添付するようエラーメッセージを付与して出品（編集）画面に戻る
・商品の画像の添付ファイル内に画像ファイル以外しかない場合にエラーメッセージを付与して出品（編集）画面に戻る
[![Screenshot from Gyazo](https://gyazo.com/27d26f6b965372001644274e1e199966/raw)](https://gyazo.com/27d26f6b965372001644274e1e199966)
=> itemモデルのテスト　及び 商品出品・編集時の不具合を修正

spec/factories/addresses.rb, spec/models/address_spec.rb, spec/models/user_spec.rb
機能テストはアプリ開発する上で必ず必要なものであるから
住所機能の確認として、以下作成。
#条件を全て満たした場合登録可
#first_nameが空だと登録できない
#last_nameが空だと登録できない
#first_name_kanaが空だと登録できない
#last_name_kanaが空だと登録できない
#postal_numberが空だと登録できない
#cityが空だと登録できない
#numberが空だと登録できない
#first_name_kanaがひらがなだと登録できない
#first_name_kanaが数字だと登録できない-1(数字)
#first_name_kanaが数字だと登録できない-2(記号)
#first_name_kanaがアルファベットだと登録できない
#last_name_kanaがひらがなだと登録できない
#last_name_kanaが数字だと登録できない-1
#last_name_kanaが数字だと登録できない-2
#last_name_kanaがアルファベットだと登録できない
#postal_numberが8桁以上数字だと登録できない
#postal_numberが6桁以下数字だと登録できない
#postal_numberにひらがなが入ると登録出来ない
#postal_numberにカタカナが入ると登録出来ない
#postal_numberにアルファベットが入ると登録出来ない
#postal_numberに記号が入ると登録出来ない
これらのテスト結果を確認
https://gyazo.com/e01f9e3ee30955e6de20399abd112d47
=> 住所登録機能のテスト

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_trades-create.scss, app/views/trades/create.html.haml
#what
購入完了画面のビューを作成した。
#why
決済が正常に完了した場合の遷移先を用意するため。
[![Screenshot from Gyazo](https://gyazo.com/37fb70c6168d33207dc88e200aab394e/raw)](https://gyazo.com/37fb70c6168d33207dc88e200aab394e)
=> 購入完了画面のマークアップ 
