- app/models/item.rb
- app/models/shippingway.rb
- db/migrate/20200227100417_remove_shippingcharge_from_items.rb
- db/migrate/20200227101626_rename_status_num_to_ancestry.rb
- db/schema.rb
#why
開発を進めるにあたってAssociationのあるテーブル間に用途の重複したカラムを発見、不要と判断したため。
また、着払い、元払いを起点に配送方法が分岐するため、shippingwaysのstatus_numカラムをgemのancestryへ変更した方が良いと思われたため。
#what
・問題なくdb:migrateできるか。
・db:migrate後に以下状態となっているか。
　itemsテーブルよりshipping_charge_numが削除されているか。
　shippingwayテーブルのstatus_numがancestryに変更されているか。また、データ型がstring型に変更されているか。
> DBのカラム削除及びカラム名の変更

- app/models/item.rb
- app/models/shippingway.rb
- db/migrate/20200228084245_change_ancestry_to_shippingways.rb
- db/migrate/20200228102559_change_foreign_key_to_shippingway_id.rb
- db/schema.rb
- db/seeds.rb
- db/seeds/category.rb
- db/seeds/item.rb
- db/seeds/shippingway.rb
今後のアプリケーション開発の工数削減に必要なため。
seedデータ作成処理を修正しました。
- shippingwayのseedデータをancestryで保存するように対応。
- shippingwayテーブルのancestryカラムがnull不可になっていたので、null許可に変更 
- itemテーブルのshippingway_idをnull不可からnull許可に変更。
- categoryに追加するシードデータの曽孫階層にサイズを追加。
> Create seeds size and shippingways

- app/assets/stylesheets/modules/_purchase.scss
- app/assets/stylesheets/modules/_user-show.scss
- app/assets/stylesheets/modules/top_content.scss
- app/views/layouts/_header.html.haml
- app/views/layouts/_purchase-btn.html.haml
- app/views/users/show.html.haml
#why
ユーザのログアウト機能が必要なため。
#what
・ボタンを押した際にconfirm画面が起動するか。
・confirm画面で「はい」を押してログアウトできているか。
[![Screenshot from Gyazo](https://gyazo.com/1e34e4541f5277540e62feba2b41b0c4/raw)](https://gyazo.com/1e34e4541f5277540e62feba2b41b0c4)
[![Screenshot from Gyazo](https://gyazo.com/9e71d38b0d91c39ad4967b619cc6f113/raw)](https://gyazo.com/9e71d38b0d91c39ad4967b619cc6f113)
> ログアウト機能の実装

- Gemfile.lock
- app/controllers/application_controller.rb
- app/views/devise/registrations/new.html.haml
#What
・ユーザーのデータをデータベースに登録できるようにする
（ニックネーム、メールアドレス、パスワード、名前（全角）、名前カナ（全角）、生年月日
#why
・ユーザーがログインするために必要な情報を登録するため
※生年月日（birthday)はdate_filedで一つにしました。
後で修正の予定です。
> ユーザー新規登録サーバーサイド

- db/migrate/20200303102404_remove_columns_from_items.rb
rails db:migrate で 20200303102404_remove_columns_from_items.rbを
適用すると、ロールバックできなくなる現象を修正しました。
migrationの履歴を正常な状態に保つためには必要なため。
> itemテーブルのカラム編集用migrationファイルの修正

- app/assets/stylesheets/modules/_items-show.scss
- app/views/items/show.html.haml
#why
ログインしているユーザに依って、「編集ボタン」、「購入ボタン」の表示の切り替えが必要なため。
#what
・出品者がログインしているときは「編集ボタン」が表示されていること。
・他ユーザ、もしくは、ユーザログインが無い場合は「購入ボタン」が表示されていること。
出品者ログイン時
[![Screenshot from Gyazo](https://gyazo.com/3e593d3ce5ea75133310c056ce4d7123/raw)](https://gyazo.com/3e593d3ce5ea75133310c056ce4d7123)
ユーザログインなし時
[![Screenshot from Gyazo](https://gyazo.com/d41244c9d0bd14f49179d7335c0a7b2d/raw)](https://gyazo.com/d41244c9d0bd14f49179d7335c0a7b2d)
> 商品詳細画面の「編集ボタン」と「購入ボタン」の実装

- app/assets/javascripts/item-image-container.js
- app/assets/javascripts/upload.js
- app/assets/stylesheets/_item-image-container.scss
- app/views/items/new.html.haml
商品出品の際の画像をクリックアップロードで実装しました。
multiple:trueで複数投稿可能にしていますが、5枚以上フォームに入れようとしてもJS側で5枚までのバリデーションをかけています。
Gif画像チェックお願いします。
DBにもしっかり5枚までで、Itemのidと紐付いて保存されます。
[![Image from Gyazo](https://i.gyazo.com/f1fa1638bb474d6fc58cb2ea6775ca4a.gif)](https://gyazo.com/f1fa1638bb474d6fc58cb2ea6775ca4a)
画像がないとどんな商品か分からない為。
ユーザーは複数の画像を投稿したいであろうから。
> Item image upload2

- app/models/user.rb
- config/application.rb
#why
password_confirmationがpaswordと同値でなくても登録できてしまう不具合を修正。
また日本語化対応を実施。
#what
同値でない際に一致しませんのエラーが表示されるか。
▪️password_confirmationがnull
[![Screenshot from Gyazo](https://gyazo.com/bf513bf4c924dfba793c1e85e67eef53/raw)](https://gyazo.com/bf513bf4c924dfba793c1e85e67eef53)
▪️password_confirmationがpasswordと入力値が異なる
[![Screenshot from Gyazo](https://gyazo.com/5e58a5211edef0114067649cee62abf0/raw)](https://gyazo.com/5e58a5211edef0114067649cee62abf0)
▪️password_confirmationがpasswordと入力値が同値（正規入力）
[![Screenshot from Gyazo](https://gyazo.com/9da64d3fded4a0f590155b1de9e9bff1/raw)](https://gyazo.com/9da64d3fded4a0f590155b1de9e9bff1)
> ユーザ登録のvalidationの一部機能が停止していたためdebug

- app/assets/javascripts/payjp.js
#why
クレジットカードをマイページから登録しようとした際に、送信ボタンを押しても初回のみボタンが動作しないバグがあったため。
#what
マイページから移動し、そのままクレジットカードの登録ができるかどうか。
[![Screenshot from Gyazo](https://gyazo.com/6f8a073f1e0a808c01b2abce82d6ad25/raw)](https://gyazo.com/6f8a073f1e0a808c01b2abce82d6ad25)
[![Screenshot from Gyazo](https://gyazo.com/1cbd83ddf4acf508191b247d974a29fd/raw)](https://gyazo.com/1cbd83ddf4acf508191b247d974a29fd)
> getメソッドでのページ遷移時にjQueryが無効になるバグの修正

- app/helpers/trades_helper.rb
- app/views/items/show.html.haml
- app/views/trades/new.html.haml
- spec/factories/addresses.rb
- spec/models/address_spec.rb
- spec/models/trade_spec.rb
商品を購入するにはユーザーがサインインしている必要があり、
カード情報とアドレス情報の両方が必要であるため。
テストコードでは、belong_toのテストのほかに
has_manyのテストをする必要があるため。
tradeモデルのテストでは、belongs_to で定義している外部キー(null不可)に
必須入力のバリデーションを定義すると、RSpecでエラーになってしまうため。
購入画面へ行くために、商品詳細画面でユーザーのサインイン判定を追加しました。
また、購入画面では、購入ボタンを表示／非表示にする処理を追加しました。
ビューで判定するのですが、変数名をそのまま扱うたと可読性が下がるので、
ヘルパーで制御をしています。
PayJpでテストカードを使用している限りでは、カード情報が１つしか
登録できないため、クレジットカード情報の変更画面へのリンクは削除しました。
has_manyのテストコードはaddressnモデルで一対多にある 
itemモデルとtradeモデルのテストをしています。
tradeモデルについては、belongs_toの外部キーに対しては
バリデーションでの必須入力チェックを除外して、失敗テストも削除しました。
> 購入画面、購入ボタンの表示／非表示処理の実装と、has_manyのテストコードを追加。

- app/views/devise/sessions/new.html.haml
#what
・ログイン時のエラーメッセージの表示
・flashオブジェクトの利用
#why
・ユーザーが登録を誤った時に間違いを分かりやすく知らせるため
下記はエラーの動画です。
https://gyazo.com/15a83f178141f13e63002e5e3be37096
> ログイン時のエラーメッセージ

- app/controllers/tops_controller.rb
- app/controllers/trades_controller.rb
- app/helpers/items_helper.rb
- app/helpers/trades_helper.rb
- app/models/item.rb
- app/models/trade.rb
- app/views/tops/index.html.haml
- app/views/trades/new.html.haml
ショッピングサイトを構築において、対応が必須であるため。
次の対応をしました。
1. 購入後の商品で購入画面へ移動してしまっても、商品が購入できないように対応。
　urlを直接叩いて画面を表示しても購入できないようにした。
[![Screenshot from Gyazo](https://gyazo.com/886ce3690f8b35390fb11d2043029a86/raw)](https://gyazo.com/886ce3690f8b35390fb11d2043029a86)
1. トップページでは出品中の商品のみを表示するように修正。
1. 金額の表記揺れを「¥ 10,000」となるように矯正。
[![Screenshot from Gyazo](https://gyazo.com/d123f918782b12704fad84c1c3e4282a/raw)](https://gyazo.com/d123f918782b12704fad84c1c3e4282a)
[![Screenshot from Gyazo](https://gyazo.com/a251401d0632499480b232283165d889/raw)](https://gyazo.com/a251401d0632499480b232283165d889)
[![Screenshot from Gyazo](https://gyazo.com/9b9d6ec1b07f913347dc1c3e8d6c98f0/raw)](https://gyazo.com/9b9d6ec1b07f913347dc1c3e8d6c98f0)
> 購入済み商品の再購入防止と商品表示の微修正。

- app/assets/stylesheets/modules/_items-show.scss
- app/helpers/items_helper.rb
- app/helpers/trades_helper.rb
- app/views/items/show.html.haml
- app/views/tops/index.html.haml
#why
登録した商品の詳細を表示し、以下ができるよう表示を変更する必要があるため。
・登録したユーザで編集、削除
・他ユーザで購入
・売約済みアイテみは売約済みであることがわかる
#what
・登録ユーザで閲覧した場合は編集、削除ボタンが表示されていること。
・未売約の商品を閲覧した場合は他ユーザで購入ボタンが表示されていること。
・売約済み商品を閲覧した場合は売約済みのボタンが表示されていること。
商品詳細
[![Screenshot from Gyazo](https://gyazo.com/bef130780eb30eb34fc9d375f56dafbd/raw)](https://gyazo.com/bef130780eb30eb34fc9d375f56dafbd)
他ユーザでみた場合
[![Screenshot from Gyazo](https://gyazo.com/33e26510a4236d50f8472b53258b3aac/raw)](https://gyazo.com/33e26510a4236d50f8472b53258b3aac)
商品購入後
[![Screenshot from Gyazo](https://gyazo.com/705dddde7bc9ad72f331c9d2afd0c721/raw)](https://gyazo.com/705dddde7bc9ad72f331c9d2afd0c721)
> 商品詳細ページの再修正

- app/controllers/trades_controller.rb
- app/helpers/trades_helper.rb
- app/views/trades/new.html.haml
rails 5.2 以降のバージョンでは、formのヘルパーメソッドは
「form_with」が推奨されているため。
購入済の場合は、foamを生成しないように修正しました。
さらに、form_tagからform_withへ変更しました。
ただし、form内に渡しているのは、tradeテーブルの外部キー
(user_id, item_id, address_id)
のみとなっています。
価格やカード情報をfoam内に取り込んで、
購入ボタンでストロングパラメータでPOSTすることも考えましたが、
itemモデルやcardモデルのデータでもparamsで参照するrequireが「trade」となってしまうため
保留としました。
> 購入機能 form_tag から form_with へ変更

- db/migrate/20200321063638_modify_column_item_id_to_trades.rb
- db/schema.rb
同じ商品(item)を複数回購入させないようにするため。
前回の対応では、購入済みの商品を出品一覧から表示させないように対応
しましたが、tradesテーブルのitemi_idにUnique制約をつけてなかったので
追加しました。
> 購入機能 多重購入防止機能の追加実装(item_idをUniqueにする)

- app/models/item.rb
- app/models/trade.rb
- spec/factories/addresses.rb
- spec/factories/items.rb
- spec/factories/trades.rb
- spec/factories/users.rb
- spec/models/trade_spec.rb
エンジニアとして、テストコードの作成は必須のため。
購入機能(tradeモデル)の成功テストと失敗テストを実装しました。
バリデーションに次のように変更しました。
user_id,address_id,status_numを必須入力としています。
item_idは必須入力と重複不可としています。
user, address, item のfactoryデータは、
tradeモデルのassociationに対応するために新しく追加してあります。
[![Screenshot from Gyazo](https://gyazo.com/3ba4ab1e767316b1e938770cf6520d20/raw)](https://gyazo.com/3ba4ab1e767316b1e938770cf6520d20)
> 購入機能 成功テストと失敗テストの実装

- app/controllers/addresses_controller.rb
出品もしくは購入で使用した住所が削除できてしまうので
削除できないように対応が必要。
addresses_controllerのdestroyアクションにitemとtradeの存在したら
addressを消せないように対応した。
[![Screenshot from Gyazo](https://gyazo.com/8becd5d654dad3a72c3227d45f14006a/raw)](https://gyazo.com/8becd5d654dad3a72c3227d45f14006a)
> 出品済みまたは購入済みの住所を削除できないように対応(issue 106の対応)

- app/controllers/addresses_controller.rb
購入後、発送前に住所の改ざんができないようにするため。
編集しようとするアドレスが購入済みであるかを検知して、
存在する場合は編集ができないようにした。
[![Screenshot from Gyazo](https://gyazo.com/50f12ccb55ec02536306f3383c856ac5/raw)](https://gyazo.com/50f12ccb55ec02536306f3383c856ac5)
> 購入済商品がある場合は住所が変更できないようにする(Issue #108の対応)

- app/assets/stylesheets/modules/trades_new.scss
- app/views/trades/new.html.haml
#what
購入確認画面のビューを実装した。
・購入者が支払情報を登録していない場合は、登録が必要。
・購入者が配送情報を登録していない場合は、登録が必要。
・購入者が支払情報と配送情報が登録している場合のみ、購入ボタンが表示される。
・商品が他の人に購入されている場合は「この商品は売約済みです。」と戻るボタンが表示される。
購入完了、購入失敗は別のプルリクで出します。
#why
購入予定の商品について、購入前に今一度確認するため。
購入者に必要な情報を入力させるため。
https://gyazo.com/630668a3f77e1c79feae223c1616e6f1
https://gyazo.com/585919db7d0a36573521e7674770e0a7
https://gyazo.com/67615176a1673a86062d1a58dc8cf4fb
> 購入確認画面のマークアップ 

- app/assets/stylesheets/modules/_trades-fail.scss
- app/views/trades/fail.html.haml
#what
購入に失敗した時のビューを実装した。
#why
支払方法が有効でない場合など、決済が正常に完了しないことも想定されるため。
[![Screenshot from Gyazo](https://gyazo.com/022a40de7463993627a8e9c2dc2b14c2/raw)](https://gyazo.com/022a40de7463993627a8e9c2dc2b14c2)
> 購入失敗画面のマークアップ 

- app/assets/stylesheets/_header.scss
- app/controllers/items_controller.rb
- app/views/items/edit.html.haml
- app/views/items/new.html.haml
#why
各Issueで報告された不具合の修正のため。
#what
issue#119
・販売価格が規定値(¥10,000,000)以上の場合エラーとなる。
　→最大値9,999,999の制限を追加
・必要な情報が不足していた場合にエラーとなる。
※修正後GIF動画
[![Screenshot from Gyazo](https://gyazo.com/d11a9d7a8729b45dac8193cc7f0e7f52/raw)](https://gyazo.com/d11a9d7a8729b45dac8193cc7f0e7f52)
issue#120 
・新規会員登録ボタンのlength不足。
※修正後スクリーンショット
[![Screenshot from Gyazo](https://gyazo.com/7244cc52c7ff91d375e863ac28698b83/raw)](https://gyazo.com/7244cc52c7ff91d375e863ac28698b83)
issue#121
・ユーザのアドレス登録がないまま出品しようとした際にエラーとなる。
※修正後GIF動画
　[![Screenshot from Gyazo](https://gyazo.com/c6c749e0694cec2c291581ff29ac46de/raw)](https://gyazo.com/c6c749e0694cec2c291581ff29ac46de)
issue#125
・商品情報を一切入力しないまま出品しようとするとエラーとなる。
※修正後GIF動画
[![Screenshot from Gyazo](https://gyazo.com/096b5c030c9b6598c0603efed9692bd1/raw)](https://gyazo.com/096b5c0 …
> issue #119、#120、#121、#125の修正パッチ

- app/assets/javascripts/items.js
- app/assets/stylesheets/_item-image-container.scss
#why
編集ボタンが存在するものの現在は機能を実装していないため、ユーザビリティを考慮して一旦消去する。
#what
出品画面と編集画面で編集ボタンが消去されているか。
※出品画面
[![Screenshot from Gyazo](https://gyazo.com/635640b3bb88729b3656ddcb1e1e8a69/raw)](https://gyazo.com/635640b3bb88729b3656ddcb1e1e8a69)
※編集画面
[![Screenshot from Gyazo](https://gyazo.com/06197cedf33ae8d3fda3d6e288596082/raw)](https://gyazo.com/06197cedf33ae8d3fda3d6e288596082)
> issue #127の修正パッチ

- app/assets/javascripts/items.js
- app/assets/stylesheets/modules/_items.scss
- app/controllers/items_controller.rb
- app/helpers/items_helper.rb
- app/views/items/edit.html.haml
- app/views/items/new.html.haml
- app/views/tops/index.html.haml
出品者が商品の手数料と販売利益を把握出来るようにすることが必要なため。
商品出品、商品編集に対応するために、下記に通りに修正した。
1. items.jsのインデントが正しくない箇所を修正。
1. 販売価格を入力後に、販売手数料と販売利益を計算するように対応。
1. 販売手数料、販売利益の表示用にCSSを編集。
1. @item.feerateは、インスタンス変数初期化時に設定するように対応。
1. @item.price, @item.profit_]priceがnilの時の処理を修正。
1. @item.price, @item.profit_]priceがnilの時の処理を修正。
1. トップ画面の「ピックアップブランド」での商品表示にも『soldout』に対応。
[![Screenshot from Gyazo](https://gyazo.com/4996fcda0977e449d617262a7fcb5d74/raw)](https://gyazo.com/4996fcda0977e449d617262a7fcb5d74)
[![Screenshot from Gyazo](https://gyazo.com/6ff6e928df94ab6546896c067afd3f70/raw)](https://gyazo.com/6ff6e928df94ab6546896c067afd3f70)
> 商品出品、商品編集で販売手数料、販売利益の表示に対応(ISSUE#124)

- app/assets/javascripts/items.js
- app/controllers/items_controller.rb
- app/views/items/edit.html.haml
#why
１枚のみ画像がある商品で画像を追加後に既存の画像を削除して編集した際に商品登録できない不具合があり、修正の必要がある。
#what
１枚のみ画像がある商品で画像を追加後に既存の画像を削除して編集した際に画像が差し替えられること。
[![Screenshot from Gyazo](https://gyazo.com/d7432fd4f1f08aa860a41a28c1eac468/raw)](https://gyazo.com/d7432fd4f1f08aa860a41a28c1eac468)
> issue #129の修正
